
package models;

import java.net.URL;

import lombok.AllArgsConstructor;
import lombok.Data;

@AllArgsConstructor
@Data
public class SearchResult {
    /*
     * hashCode() and equals() implementations were auto generated by Eclipse
     * around the 'url' field.
     *
     * Required to ensure that our results are unique by 'url'
     */
    private final URL url;

    private final String title;

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((url == null) ? 0 : url.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;
        SearchResult other = (SearchResult) obj;
        if (url == null) {
            if (other.url != null) return false;
        } else if (!url.equals(other.url)) return false;
        return true;
    }
}
